name: Build Zip File
on: 
  release:
    types: [published]
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        path: 'ControllerTweaks'
    
    - name: Zip release
      run: 7z a esoui_release.zip * -xr!*.git* -xr!*.vscode*
    
    - name: Attach zip to release
      uses: Shopify/upload-to-release@v1.0.1
      with:
        name: esoui_release.zip
        path: esoui_release.zip
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: ESO UI Publish
      uses: Xeio/esoui-deploy-action@main
      with:
        addon-file-path: ./ControllerTweaks/ControllerTweaks.txt
        upload-zip-path: esoui_release.zip
        addon-id: 2517
        eso-ui-api-key: ${{secrets.ESOUI_API_TOKEN}}
        github-api-key: ${{secrets.github_token}}
